### ISSUE TITLE
old php version issue

### ISSUE THREAD

**Issue by atherdon** [onetsp/RecipeParser#9]
Hello, big thanks for this library!
I`ve tried to add your functionality to a wordpress plugin, but got an error when have an old php installed on hosting. 
Our plugin works fine in php 5.3.3 but have an error on php 5.2.17.
Issue can be found in class_recipe_parser.php on line #110.

Thanks again!

**Comment by onetsp** [comment]
Will not be back porting to PHP 5.2.
